/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bcc7de",
        "background": "#fbf8fa",
        "tertiary-fixed-dim": "#ddc39d",
        "secondary": "#505f76",
        "on-tertiary-fixed": "#271902",
        "on-error": "#ffffff",
        "surface-bright": "#fbf8fa",
        "primary-fixed": "#d8e3fb",
        "inverse-on-surface": "#f3f0f2",
        "on-primary-fixed": "#111c2d",
        "surface": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "secondary-fixed": "#d3e4fe",
        "secondary-container": "#d0e1fb",
        "on-surface-variant": "#45474c",
        "surface-tint": "#545f73",
        "on-primary-container": "#8590a6",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#1e1200",
        "primary-container": "#1e293b",
        "inverse-primary": "#bcc7de",
        "tertiary-container": "#35260c",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#a38c6a",
        "surface-variant": "#e4e2e3",
        "tertiary-fixed": "#fadfb8",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container": "#f0edef",
        "error-container": "#ffdad6",
        "on-secondary-container": "#54647a",
        "surface-container-highest": "#e4e2e3",
        "error": "#ba1a1a",
        "on-surface": "#1b1b1d",
        "on-background": "#1b1b1d",
        "on-primary-fixed-variant": "#3c475a",
        "outline": "#75777d",
        "primary": "#091426",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#303032",
        "surface-dim": "#dcd9db",
        "surface-container-high": "#eae7e9",
        "outline-variant": "#E7EAF0",
        "on-tertiary-fixed-variant": "#564427",
        "surface-container-low": "#f5f3f4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "14px",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "container-padding-mobile": "1rem",
        "gutter": "1.5rem",
        "container-padding-desktop": "24px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
